class Items {
    constructor(image, name, description, category) {
        this.image = image;
        this.name = name;
        this.description = description;
        this.category = category;
    }
}


let item1 = new Items("./assets/mcbook_pro.jpeg", "MacBook Pro", "Ordinateur portable puissant avec écran Retina et processeur rapide.", "Electronique"); 
let item2 = new Items("./assets/iphone12.jpg", "iPhone 12", "Téléphone haut de gamme avec un superbe écran et une caméra avancée.", "Electronique"); 
let item3 = new Items("./assets/vtt.jpg", "VTT Trek", "Vélo tout terrain robuste pour des aventures en montagne.", "Sport"); 
let item4 = new Items("./assets/nikon.jpg", "Nikon D850", "Appareil photo p^rofessionnel avec une résolution exceptionnelle et de nombreuses fonctionnalités avancée.", "Electronique"); 
let item5 = new Items("./assets/ps5.jpg", "PlayStation 5", "Console de jeux de nouvelle génération offrant des graphismes impressionnants et une expérience de jeu immersive.", "Jeux"); 
let item6 = new Items("./assets/apple_watch.jpg", "Apple Watch Series 6", "Montre connectée avec suivi de la condition physique, notifications et fonctionnalités avancées.", "Electronique"); 
let item7 = new Items("./assets/ipad_pro.jpg", "iPad Pro", "Tablette haut de gamme avec un écran Retina et des performances exceptionnelles.", "Electronique"); 
let item8 = new Items("./assets/guitare.jpg", "Guitare acoustique", "Guitare en bois de qualité supérieure avec un son riche et une belle finition.", "Musique"); 
let item9 = new Items("./assets/scooter.jpg", "Xiaomi Mi Electric Scooter", "Ordinateur portable puissant avec écran Retina et processeur rapide.", "Electronique"); 
let item10 = new Items("./assets/jbl.jpg", "JBL Charge 4", "Enceinte portable étanche avec un son puissant et une longue autonomie de batterie.", "Electronique"); 

let item11 = new Items("./assets/0818279025057_h_f_l_0.webp", "GoPro Hero 9 Black", "Caméra polyvalente pour capturer des vidéos et des photos d'aventures sportives et en plein air.", "Electronique");
let item12 = new Items("./assets/Nespresso Vertuo.avif", "Nespresso Vertuo", "Machine à café automatique avec une large variété de capsules pour préparer de délicieux expressos.", "Cuisine");
let item13 = new Items("./assets/SONY WH 100 XM4.avif", "Sony WH-1000XM4", "Casque audio haut de gamme avec réduction de bruit active et une qualité sonore exceptionnelle.", "Electronique");
let item14 = new Items("./assets/DJI MAVIC AIR 2.jpg", "DJI Mavic Air 2", "Drone compact et puissant pour capturer des images aériennes et des vidéos de haute qualité", "Electronique");
let item15 = new Items("./assets/TheNorthFaceTerra65.webp", "The North Face Terra 65", "Sac à dos spacieux et confortable pour les randonnées de plusieurs jours en montagne.", "Sport");
let item16 = new Items("./assets/Catan.avif", "Catan", "Jeu de stratégie populaire où les joueurs tentent de coloniser une île en collectant des ressources.", "Jeux");
let item17 = new Items("./assets/irobotroomba980.jpg", "iRobot Roomba 980", "Robot aspirateur autonome qui nettoie les sols avec efficacité et programmable via une application.", "Electronique");
let item18 = new Items("./assets/IpodTouch", "IPod Touch", "Lecteur de musique compact avec écran tactile et une grande capacité de stockage.", "Electronique");
let item19 = new Items("./assets/ASUS ROG Swift.jpeg", "ASUS ROG Swift PG279Q", "Moniteur haute résolution avec un taux de rafraîchissement élevé pour une expérience de jeu fluide.", "Jeux");
let item20 = new Items("./assets/Samsonite Spinner.jpeg", "Samsonite Spinner", "Valise durable et pratique avec des roulettes pour faciliter les déplacements.", "Transport");

const Item21 = new Items("https://www.somagic.fr/1655-medium_default/stila-electrique.jpg", "Plancha électrique", "Plancha électrique pour griller et cuisiner des aliments de manière saine et savoureuse.", "cuisine");
const Item22 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Flexcofitness.fr%2Fwp-content%2Fuploads%2F2019%2F12%2FAppareil-de-musculation-Plate-Loaded-Incline-Press-Lexco-mod%25C3%25A8le-LS-516.jpg&tbnid=gr6g0nsGmabBzM&vet=12ahUKEwiNnrKB9Jz_AhX1pUwKHWjFDmoQMygVegUIARCpAw..i&imgrefurl=https%3A%2F%2Flexcofitness.fr%2Fproduct%2Fappareil-de-musculation-incline-press-lexco-modele-ls-516%2F&docid=LonFfDf25tI70M&w=530&h=546&q=image%20appareil%20fitness&ved=2ahUKEwiNnrKB9Jz_AhX1pUwKHWjFDmoQMygVegUIARCpAw", "Appareil de fitness", "Appareil d'exercice pour le cardio-training et le renforcement musculaire à domicile.", "Sport");
const Item23 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cornerluxe.com%2F15197-thickbox_default%2Fsac-a-main-louis-vuitton-speedy-35-m41107-en-toile.jpg&tbnid=PP4mIk82NElgoM&vet=12ahUKEwi_xYDH9Jz_AhXyoUwKHS5jCLIQMygWegUIARD4AQ..i&imgrefurl=https%3A%2F%2Fwww.cornerluxe.com%2Ffr%2Fvente-sacs-a-main%2F14682-sac-a-main-louis-vuitton-speedy-35-m41107-en-toile.html&docid=IXvXd6zbTZYWQM&w=1000&h=1000&q=louis%20vitton%20speedy&ved=2ahUKEwi_xYDH9Jz_AhXyoUwKHS5jCLIQMygWegUIARD4AQ", "Sac à main", "Sac à main élégant et intemporel en cuir de haute qualité.", "Esthétique");
const Item24 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fi8.amplience.net%2Fi%2Fepsonemear%2F27258_productpicture_hires_ecotank&tbnid=AaLSfSNY8AoBjM&vet=12ahUKEwj7i4219Zz_AhX_nCcCHaKXC-UQMygAegUIARC5Aw..i&imgrefurl=https%3A%2F%2Fwww.epson.fr%2Ffr_FR%2Fproduits%2Fimprimantes%2Finkjet%2Fgrand-public%2Fecotank-et-2720%2Fp%2F27258&docid=OMtSoMXcQxjtrM&w=2860&h=1629&q=Epson%20EcoTank%20ET-2720&ved=2ahUKEwj7i4219Zz_AhX_nCcCHaKXC-UQMygAegUIARC5Aw", "Imprimante multifonction", "Imprimante, scanner et photocopieur sans cartouches d'encre, avec une grande capacité de réservoir.", "Electronique");
const Item25 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.e-ping-pong.com%2Fimages%2Fproduit%2Fbig%2FTABLE-DE-PING-PONG-CORNILLEAU-600X-CROSSOVER-OUTDOOR-LOISIR-1.jpg&tbnid=8lmZY4ULDJbjpM&vet=12ahUKEwimlvLDh53_AhXJvicCHd6LDboQMygBegUIARDpAw..i&imgrefurl=https%3A%2F%2Fwww.e-ping-pong.com%2Ftable-de-ping-pong-cornilleau-600X-crossover-outdoor-exterieur-loisir-prd.php&docid=-bxlpSAS3Oph4M&w=988&h=498&q=table%20de%20ping-pong&ved=2ahUKEwimlvLDh53_AhXJvicCHd6LDboQMygBegUIARDpAw", "Table de ping-pong", "Table de ping-pong de qualité professionnelle pour des parties amusantes en intérieur ou en extérieur.", "Sport");
const Item26 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cdiscount.com%2Fpdt2%2F6%2F4%2F6%2F1%2F350x350%2FAUC5061181859646%2Frw%2Fkit-de-peinture-acrylique-castle-art-supplies-mda.jpg&tbnid=QtTlKCPjrWgodM&vet=12ahUKEwj_9IuLiJ3_AhUip0wKHeHgDPEQMygHegUIARCoAw..i&imgrefurl=https%3A%2F%2Fwww.cdiscount.com%2Farts-loisirs%2Fbeaux-arts%2Fkit-de-peinture-acrylique-castle-art-supplies-mda%2Ff-161010101-auc5061181859646.html&docid=ti2DFMPVSZu-dM&w=700&h=700&q=kit%20de%20peinture%20artistique&ved=2ahUKEwj_9IuLiJ3_AhUip0wKHeHgDPEQMygHegUIARCoAw", "Kit de peinture artistique", "Ensemble complet de peintures, pinceaux et toiles pour les amateurs d'art.", "Art");
const Item27 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.osmoz.fr%2FPublic%2FFiles%2Fperfume%2Fimage_fragrance_shalimar_caaa1f9f35_600.jpg&tbnid=fUMckZeiJsHRsM&vet=12ahUKEwjPjq67iJ3_AhUJpicCHcRsDBMQMygTegUIARCRBQ..i&imgrefurl=https%3A%2F%2Fwww.osmoz.fr%2Finspiration%2Fosmoz-magazine%2F411%2Fparfum-luxe-femme&docid=vdbkhKS6vqpCQM&w=600&h=600&q=parfum%20de%20luxe&ved=2ahUKEwjPjq67iJ3_AhUJpicCHcRsDBMQMygTegUIARCRBQ", "Parfum de luxe", "Parfum féminin élégant et raffiné avec des notes florales et orientales.", "Esthétique");
const Item28 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fcontents.mediadecathlon.com%2Fp2264018%2Fk%240430c8019ec00681764a3e0eee8c38d0%2Fsq%2Fpaire-de-talkie-walkies-rechargeables-par-usb-5-km-wt100.jpg%3Fformat%3Dauto%26f%3D800x0&tbnid=sW00zPoqmVTn3M&vet=12ahUKEwj0qovTiJ3_AhUfmycCHU9dDZ0QMygKegUIARCJBA..i&imgrefurl=https%3A%2F%2Fwww.decathlon.fr%2Fp%2Fpaire-de-talkie-walkies-rechargeables-par-usb-5-km-wt100%2F_%2FR-p-324515&docid=wLgVc7i6SYMl8M&w=800&h=800&q=talkie%20walkie&ved=2ahUKEwj0qovTiJ3_AhUfmycCHU9dDZ0QMygKegUIARCJBA", "Talkie-walkie", "Talkie-walkie étanche pour une communication fiable lors des activités en plein air.", "Electronique");
const Item29 = new Items("https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.bfmtv.com%2Fcomparateur%2Fwp-content%2Fuploads%2F2020%2F09%2Funnamed-15-300x158.png&tbnid=kJnEm7YkVpi1vM&vet=12ahUKEwilmKv6iJ3_AhV7vicCHabXBRkQMygAegUIARDoAw..i&imgrefurl=https%3A%2F%2Fwww.bfmtv.com%2Fcomparateur%2Fmeilleures-enceintes-intelligentes-test-comparatif%2F&docid=NrlIAP4A2JlZIM&w=300&h=158&q=enceinte%20intelligente&ved=2ahUKEwilmKv6iJ3_AhV7vicCHabXBRkQMygAegUIARDoAw", "Enceinte intelligente", "Enceinte connectée avec commande vocale et intégration d'assistants virtuels.", "Electronique");
const Item30 = new Items("https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.gamecash.fr%2Fthe-legend-of-zelda-breath-of-the-wild-e84747.html&psig=AOvVaw0oTj5zhYxI22HJAFsQvYrx&ust=1685537119744000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCODV9puJnf8CFQAAAAAdAAAAABAS", "Jeu vidéo", "Jeu d'aventure épique dans un vaste monde ouvert, rempli d'exploration et de défis.", "Jeu");




